### ISSUE TITLE
Foreign Key linking in parent fails unless make temp name for child.

### ISSUE THREAD

**Issue by OneOfMany07** [django-nonrel/django#6] opened 2013-06-28 19:34 UTC
I'm switching from mongoengine to mongodbengine (nonrel) hoping to become more standardized, but something that worked in the old system doesn't with the current 1.4 branch.

In a view I'm trying to link up a child object to a parent and this code doesn't create the foreign key link...

(model.py)

``` python
class Child(Model):
    a = ...

class Parent(Model):
    child = ForeignKey(Child, null=True)
```

(view.py)

``` python
if not parent.child:
    parent.child = Child()
parent.child.a = ...
parent.child.save()
parent.save()
```

I get a new child object with the attribute a set, but the parent doesn't have the ID of the new child object in the child attribute (it has null).  But this version does work.

``` python
if not parent.child:
    child = Child()
else:
    child = parent.child
child.a = ...
child.save()
parent.child = child
parent.save()
```

No idea why, but I assume there is a subtle bug here.  And as I said with Django 1.4.2 and mongoengine (+ parts) it worked fine.

**Comment by aburgel** [comment] 2013-06-28 19:38
What happens when do run the code that doesn't work? Do you get an error or something? Is the data getting saved to the database correctly?

**Comment by OneOfMany07** [comment] 2013-06-28 19:40
I get the new child object I expected, and no errors.  The display page just doesn't show the child, and that is because there is no link between them (the id is still null for parent.child...the last parent.save() doesn't do anything).

**Comment by aburgel** [comment] 2013-06-28 20:58
So after a bit of research, it looks like this is a known issue with django and not something caused by nonrel. Take a look at this bug report: https://code.djangoproject.com/ticket/8892

I'm going to close this issue, but reopen if you think I'm wrong.

**Closed as completed by aburgel** 2013-06-28 20:58 UTC
